### ISSUE TITLE
Add a WildFly Swarm tutorial

### ISSUE THREAD

**Issue by l0rd** [eclipse/che-docs#209] opened 2017-04-14 00:56 UTC
That's related to PR https://github.com/eclipse/che/pull/4544 that introduced the WildFly Swarm stack.

**Comment by themr0c** [comment] 2020-03-12 10:04
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:04 UTC
Labels: kind/enhancement
