### ISSUE TITLE
OpenShift plugin install page doesn't explain how to copy the binaries

### ISSUE THREAD

**Issue by rimolive** [eclipse/che-docs#65] opened 2017-01-17 12:15 UTC
Link: https://www.eclipse.org/che/docs/openshift/config/index.html

It only mentions to download the Binaries and that's it. What should I do with it?

**Comment by JamesDrummond** [comment] 2017-01-31 22:30
Related to https://github.com/eclipse/che-docs/issues/76

**Comment by eivantsov** [comment] 2017-02-01 07:24
@JamesDrummond i do not think this is a correct title. We need a few lines on how to start Tomcat and that's it. 

@bmicklea the label should be docs not bug

**Comment by bmicklea** [comment] 2017-02-01 16:56
Since this is a docs repo we'll use `bugs` to indicate a gap in docs that shouldn't be there and `enhancement` to indicate an expansion of the docs.

**Comment by JamesDrummond** [comment] 2017-02-02 14:01
@eivantsov I think Ilya is working on this right? I think bug label might be right in this case as brad mentioned. Docs is general term.

**Comment by themr0c** [comment] 2020-03-12 10:01
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:01 UTC
Labels: Che-6, kind/bug
