### ISSUE TITLE
Remove electron references from docs

### ISSUE THREAD

**Issue by TylerJewell** [eclipse/che-docs#267] opened 2017-07-26 15:54 UTC
We are not supporting the electron client and should remove any reference to binaries on it here:
http://www.eclipse.org/che/docs/ide/electron/index.html

**Comment by bmicklea** [comment] 2017-12-04 14:42
Closing as duplicate of: https://github.com/eclipse/che-docs/issues/319

**Closed by bmicklea** 2017-12-04 14:42 UTC
