### ISSUE TITLE
CHE_MAIL_HOST_PORT vs CHE_MAIL_PORT

### ISSUE THREAD

**Issue by davidwindell** [eclipse/che-docs#308] opened 2017-10-27 13:08 UTC
[Docs](https://www.eclipse.org/che/docs/user-management/organizations/index.html#email-notifications) say use `CHE_MAIL_PORT`, [che.env](https://github.com/eclipse/che/blob/master/dockerfiles/init/manifests/che.env) says `CHE_MAIL_HOST_PORT`. 

Also, `CHE_MAIL_SMTP_STARTTLS_ENABLE` doesn't exist in che.env

There seems to be a lot of confusion between the docs and the app about exactly what the available MAIL_ options are.

**Comment by bmicklea** [comment] 2017-11-01 18:41
@eivantsov can you comment?

**Comment by themr0c** [comment] 2020-03-12 10:20
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant. 

See: https://www.eclipse.org/che/docs/che-7/configuring-authorization/#configuring-smtp-and-email-notifications

**Closed by themr0c** 2020-03-12 10:20 UTC
Labels: Che-6, kind/question
