### ISSUE TITLE
Create a tutorial for vert.x 

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#89] opened 2017-01-23 13:07 UTC
With the addition of a vert.x stack into the default Che assembly, it would be nice to author a tutorial about Vert.x in Che and maybe reference it onto Vert.x documentation as well.

See initial PR: https://github.com/eclipse/che/pull/3843

**Comment by themr0c** [comment] 2020-03-12 10:01
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:01 UTC
Labels: kind/docs
