### ISSUE TITLE
Document requirements to work remote Theia plugin feature.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse/che-docs#670] opened 2019-01-29 10:38 UTC
@eivantsov investigated that remote Theia plugin doesn't work on the minikube/minishift. The problem was that containers had no ability to communicate between each other (che and remote plugin). It was solved by starting `minikube start` with --docker-opt userland-proxy=false. We need apply this information to docs.

**Comment by AndrienkoAleksandr** [comment] 2019-01-29 11:02
https://github.com/eclipse/che/issues/12526#issuecomment-458489204

**Comment by themr0c** [comment] 2020-03-12 09:57
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 09:57 UTC
Labels: kind/task
