### ISSUE TITLE
Remove references to Electron client (no longer supported)

### ISSUE THREAD

**Issue by bmicklea** [eclipse/che-docs#319] opened 2017-12-04 14:42 UTC
We are not supporting the electron client and should remove any reference to binaries on it here:
http://www.eclipse.org/che/docs/ide/electron/index.html

**Comment by bmicklea** [comment] 2017-12-04 14:42
@eivantsov can you take care of this please?

**Comment by themr0c** [comment] 2020-03-12 10:21
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:21 UTC
Labels: Che-6, kind/bug, kind/docs
