### ISSUE TITLE
Create page for Terminal and Processes panel

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#46] opened 2017-01-08 18:52 UTC
Similar to the pages on this section:
https://github.com/codenvy/che-docs/tree/master/src/main/_docs/use-che-as-an-ide

We need to add a new page about the Process panel. This panel is not covered in any docs.
Items to cover:
- How to get a terminal
- How to split
- Various display options in the toolbar
- Double click on panel for the fullscreen mode

**Comment by JamesDrummond** [comment] 2017-02-17 16:20
@slemeur Some of these are already done in https://eclipse.org/che/docs/ide/editor-settings/index.html

**Comment by themr0c** [comment] 2020-03-12 10:00
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:00 UTC
Labels: Che-6, kind/enhancement, severity/P1
