### ISSUE TITLE
Create plugins authoring guides, documentations and resources

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#335] opened 2018-01-12 14:15 UTC
#### Motivation
The goal of this epic is to provide a set of resources that Eclipse Che community can leverage about authoring plugins.

**Note:** This documentation will target the next gen Che (see https://github.com/eclipse/che/issues/8266)

#### Documentation
The documentation around Che extensibility must cover:
- Principles and architecture of Che extensibility
- APIs documentation
- Plugin lifecycle
- Packaging of a plugin
- Plugin examples
 
#### Guides
Guides (or tutorial) must be provided for those topics:
- Develop an Hello World plugin
- Developing IDE on Theia for Che's workspaces
- Packaging a Language Server in Che

#### Resources
We are looking to create material that we can use in order to evangelize the extensibility of Eclipse Che and get new contributions.

We should target to create:
- Blog posts
- 101 Videos of live demos of creating plugins 
- (eventually) training material

### Linked issues
https://github.com/eclipse/che/issues/7492

**Comment by Jimmyscene** [comment] 2018-04-29 23:25
Any updates on this? I'm looking to use Che but I'll need to create a custom language server and the documentation is extremely sparse on this subject.

**Comment by slemeur** [comment] 2018-04-30 16:26
Hi @Jimmyscene .

If you are looking at documentation on how to add a language server, you should be looking here:
https://www.eclipse.org/che/docs/language-servers.html

What king of language are you willing to add? Is that by any chance something you'd like to make available to the community?

**Comment by eivantsov** [comment] 2018-04-30 16:30
@Jimmyscene docs on how to create a language server is out of Che scope. I'd first look at https://github.com/Microsoft/vscode-docs/blob/master/docs/extensions/example-language-server.md

**Comment by Jimmyscene** [comment] 2018-04-30 20:46
@slemeur It'd be for: http://robotframework.org/ and if I can get it working I'll be sure to make it available if you guys are willing to add it. 

Thanks for the docs links, I think I should be able to figure it out from the two you guys provided, I hadn't seen docs from @eivantsov, I'll see if I can get that working.

**Comment by themr0c** [comment] 2020-03-12 10:26
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.  

See: https://www.eclipse.org/che/docs/che-7/developing-che-theia-plug-ins/

**Closed by themr0c** 2020-03-12 10:26 UTC
Labels: Che-6, kind/epic
