### ISSUE TITLE
Suggestion to Add to Documentation

### ISSUE THREAD

**Issue by Rubeneruiz** [eclipse/che-docs#186] opened 2017-03-30 04:10 UTC
I have been asked to contribute to an open source project as part of an assignment for a class I am taking. I decided to review the documentation and provide my feedback in order to contribute to this project. The contents of the documentation provide a lot of detail and specific information about the product. However, I think it could be improved by adding the following suggestions:
 
- What internet browsers are supported?
- What are the maximum number of Workspaces a Che’s server can host? If multiple applications running simultaneously by multiple users may cause some performance issues.
- For a Local installation, I was not able to find information about the Linux distributions that are supported in the software requirement section. There is mention of RHEL/CentOS but there is no information about what versions are supported. Are Ubuntu, Fedora, Mint, etc supported as well?
- In the managing section, it is stated that HTTPS is not provided by Eclipse Che and that Codenvy gives the option of running the system with HTTPS and provide a SSL certificate.  I think a link to the specific section would help users. Also, for users who generate their own SSL certificate, will they be able to use Eclipse Che with HTTPS enabled?

I hope these suggestions, if implemented, provides new users with more information to encourage new developers to join and use this great open source project.

**Comment by bmicklea** [comment] 2017-04-02 11:50
@JamesDrummond - please review.

@Rubeneruiz Che can be installed on any system that supports Docker 1.11+ so we don't list distros as the list would be long and very difficult to keep accurate.

**Comment by JamesDrummond** [comment] 2017-04-02 18:29
@Rubeneruiz 
- Browser need to be a browser that supports browsers such as Chrome, Firefox or Safari. @eivantsov I cannot recall the reason for this.
- There is no maximum based on host. Performance can set max cpu usage with `CHE_DOCKER_CPUSET__CPUS` , `CHE_DOCKER_CPU__PERIOD` and `CHE_DOCKER_CPU__QUOTA`
- As long as you can run docker 1.11+ Che can run as Brad mentioned. Within workspace machines all major linux distribution can run to my knowledge. 
- HTTPS can be accomplished. @benoitf and @eivantsov would know more one specifics.

I just created a factory that you can use if you would like to contribute to the documentation. https://codenvy.io/f?name=che-codenvy-docs&user=jdrummond for repo at https://github.com/eclipse/che-docs

**Comment by bmicklea** [comment] 2017-04-03 13:26
@Rubeneruiz - it would be great if you could sign the Eclipse contributor license agreement (https://github.com/eclipse/che/wiki/Contributor-License-Agreement) and make these changes. We love outside contributors!

**Comment by themr0c** [comment] 2020-03-12 10:03
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:03 UTC
Labels: Che-6, kind/enhancement
