### ISSUE TITLE
Documentation needed to get the server

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#77] opened 2017-01-19 18:48 UTC
With 5.1.0 we removed the `Ops perspective` and we moved the server part to the dashboard.

We need to update documentation on this. See the following support issue:
https://github.com/codenvy/codenvy/issues/1563

**Comment by slemeur** [comment] 2017-01-19 18:48
Would appreciate your help on this @akurinnoy ;)

**Comment by themr0c** [comment] 2020-03-12 10:01
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:01 UTC
Labels: Che-6, kind/bug, severity/P1
