### ISSUE TITLE
Maven errors while building OpenShift plugin

### ISSUE THREAD

**Issue by rimolive** [eclipse/che-docs#66] opened 2017-01-17 12:17 UTC
I can't build the OpenShift plugin as mentioned in https://www.eclipse.org/che/docs/openshift/config/index.html.

The whole maven output is in the gist below:

https://gist.github.com/rimolive/77f9d9e400a5f9105e52a2306103c5ee

**Comment by JamesDrummond** [comment] 2017-01-31 22:30
Related to https://github.com/eclipse/che-docs/issues/76

**Comment by themr0c** [comment] 2020-03-12 10:01
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:01 UTC
Labels: Che-6, kind/bug
