### ISSUE TITLE
Editor keybindings docs needs to be updated

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#276] opened 2017-08-11 12:53 UTC
The following documentation: https://eclipse.org/che/docs/ide/editor-settings/index.html needs to be updated accordingly with the new way to configure the editor keybindings.

Since 5.6 - and the following issue https://github.com/eclipse/che/pull/4394 : the keybindings are getting their dedicated wizard available from `Assistant > Keybinding` menu.

**Comment by themr0c** [comment] 2020-03-12 10:38
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:38 UTC
Labels: Che-6, kind/docs
