### ISSUE TITLE
Add documentation to detail workspaces features

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#73] opened 2017-01-19 09:09 UTC
Current documentation on `Workspaces` are high level and not very concrete for the end-user. 
https://www.eclipse.org/che/docs/workspace/admin-intro/index.html

We should add sections to explain how to create, edit and manage workspaces from User Dashboard.

We should also update all bullets in existing section and link them to the appropriated pages.

**Comment by themr0c** [comment] 2020-03-12 10:01
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:01 UTC
Labels: Che-6, kind/enhancement, severity/P2
