### ISSUE TITLE
Add error hinting mecanism documentation to plugin guide

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#95] opened 2017-01-24 09:44 UTC
In the [developer guide for plugins](https://www.eclipse.org/che/docs/plugins/introduction/index.html) we introduce the basics to support a new language without using the language server. 

We have a section which explain syntax highlighting, code completion, but we are missing a section about code analysis and how to show error hinting in the editor

Would expect a section like this one: https://www.eclipse.org/che/docs/plugins/code-editors/index.html#code-completion on the same page.

See requested documentation on following this issue: https://github.com/eclipse/che/issues/3856

**Comment by themr0c** [comment] 2020-03-12 10:02
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:02 UTC
Labels: Che-6, kind/docs, team/ide
