### ISSUE TITLE
SDK Action documentation not up to date

### ISSUE THREAD

**Issue by hkolvenbach** [eclipse/che-docs#278] opened 2017-08-18 12:31 UTC
https://www.eclipse.org/che/docs/assemblies/sdk-actions/index.html

CurrentProject does not exist in `org.eclipse.che.ide.api.app` anymore. It should probably be `AppContext.getRootProject()`

**Comment by bmicklea** [comment] 2017-12-04 14:40
@eivantsov is this update part of the new docs you're working on?

**Comment by themr0c** [comment] 2020-03-12 10:17
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:17 UTC
Labels: Che-6, kind/docs
