### ISSUE TITLE
Clarify that VS Code extension usage using command palette is an alternative to meta.yaml way

### ISSUE THREAD

**Issue by garagatyi** [eclipse/che-docs#673] opened 2019-01-31 12:37 UTC
We have docs on how to test VS Code extension in Che Theia https://github.com/eclipse/che/wiki/CHE-7---Development-Workflow#how-to-create-and-test-a-che-7-plugin-from-an-existing-vs-code-extension
There is a description that one can deploy an extension using Theia command palette.
But next to it there is a description of how to create meta.yaml with such an extension which is complete another flow. It would be better to separate them to show that they are 2 alternatives and describe their pros and cons.

**Comment by themr0c** [comment] 2020-03-12 09:58
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 09:58 UTC
