### ISSUE TITLE
Recommended way to use a private git repository?

### ISSUE THREAD

**Issue by stianlagstad** [eclipse/che-docs#685] opened 2019-02-26 13:04 UTC
I wish to use Eclipse Che locally in Docker, and work on a private git repository that I have. Are there any up to date guide on how I should do that? I found many references to eclipse-che.readme.io, for example https://eclipse-che.readme.io/inactive#git-with-ssh, but those pages are no longer there.

What I've gotten to work so far
1. Start che: `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /local/path/:/data eclipse/che start`
2. Create a workspace
3. Try to import project -> GIT -> enter a URL like "https://my_username:my_password@bitbucket.com/my_username/my_repo.git"

But I'd rather not clone the repository using my password in plaintext like that. Maybe there's a way I can link in the ssh files I already have on my own machine so that I could use them to clone the repository inside the Che container?

Thank you!

(I've asked about something similar before, in https://github.com/eclipse/che-docs/issues/336.)

**Comment by octalmage** [comment] 2019-03-04 16:40
Yeah this seems like a basic use-case for me. I've got a project that pulls my website down using git, so it's already checked out locally. I wonder what developer wouldn't want to have a project running locally? I'd just like a docker based IDE to develop locally. If this isn't it I'll keep looking!

**Comment by slemeur** [comment] 2019-03-12 11:19
You should be able to refer to this part of the documentation:
https://www.eclipse.org/che/docs/che-6/version-control.html#generateupload-ssh-keys

**Comment by stianlagstad** [comment] 2019-03-17 13:21
Thanks! I've tried following the steps but I have some problems.

What I'm doing:
1. Click "Profile" -> "Preferences"
2. In the "SSH VCS" menu item, I click "Upload key"
3. I then enter "Host" "github.com", and select my private key. It looks like this:
![Screenshot from 2019-03-17 14-16-02](https://user-images.githubusercontent.com/4340859/54491492-454ae380-48bf-11e9-9701-eb504fc6e0ca.png)
4. I click "Upload", and then I see this:
![Screenshot from 2019-03-17 14-16-53](https://user-images.githubusercontent.com/4340859/54491497-572c8680-48bf-11e9-8691-71f5ed75dbdd.png)
5. I click "Close" and then try to click "Import project". I then get a "Failed to import project" message, and I see this in the console:
![Screenshot from 2019-03-17 14-18-23](https://user-images.githubusercontent.com/4340859/54491534-8b07ac00-48bf-11e9-8b78-e10f90e57a36.png)
6. I don't know why that happens, but I figure I can instead try to clone my project from the terminal. I try this (repository name clipped away on purpose), but it looks like the SSH key I uploaded is not used:
![Screenshot from 2019-03-17 14-19-34](https://user-images.githubusercontent.com/4340859/54491549-b7232d00-48bf-11e9-9d8f-b9619c44096b.png)

I'm sure there's something simple I'm not aware of that I have to do to make this work. Could you offer some advice?

**Comment by stianlagstad** [comment] 2019-03-19 19:34
I thought maybe that I'd have to run `ssh-add path/to/file` in the terminal within che to register the key, but I could not find it.
```
user@9e42552516a7:~/.ssh$ ls -ahl /home/user/.ssh
total 12K
drwxr-xr-x 2 user user 4.0K Mar 19 19:24 .
drwxrwxr-x 1 user root 4.0K Mar 19 19:24 ..
-rw-r--r-- 1 user user  382 Mar 19 19:24 authorized_keys
```
When I go to "Profile" -> "Preferences" -> "SSH VCS", then I do see my key in the list there. Ref ![the picture previously uploaded](https://user-images.githubusercontent.com/4340859/54491497-572c8680-48bf-11e9-8691-71f5ed75dbdd.png). Where is that uploaded key stored?

**Comment by slemeur** [comment] 2019-03-20 07:10
@vparfonov : Can you have someone from your team helping @stianlagstad ?

**Comment by vparfonov** [comment] 2019-03-20 14:41
@stianlagstad Hello, you need to check installer section in Dashboard "git credentials" shold be enabled, if not turn on it and restart workspace. It should help 
![git-credentials](https://user-images.githubusercontent.com/1636592/54693021-9dd3e800-4b2e-11e9-828e-db7c95947caa.png)

**Comment by stianlagstad** [comment] 2019-03-21 19:20
Thank you very much. That worked :) Any way I can contribute to [these docs](https://www.eclipse.org/che/docs/che-6/version-control.html#generateupload-ssh-keys) to add a section about making sure that service is toggled?

**Comment by stianlagstad** [comment] 2019-03-21 19:23
While I was able to clone my repository, I'm having some problems opening it. I'm trying to click "Import project", but then I see this:
![Screenshot from 2019-03-21 20-20-37](https://user-images.githubusercontent.com/4340859/54779230-f7174680-4c16-11e9-94ed-d3a25677d7c3.png)

When I do click import project I see this appearing in the console:
![Screenshot from 2019-03-21 20-22-22](https://user-images.githubusercontent.com/4340859/54779270-144c1500-4c17-11e9-9f30-41c2d2aae597.png)

Any advice on what I can do to open my newly cloned project?

**Comment by stianlagstad** [comment] 2019-04-10 11:00
Please let me know if there's any additional information I can provide, or tests I can perform, to help debug the issue.

**Comment by themr0c** [comment] 2020-03-12 09:59
We are closing this issues because we believe it is outdated (does not apply to Che 7). Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 09:59 UTC
Labels: kind/question

**Comment by sharmahr** [comment] 2020-05-16 03:49
> We are closing this issues because we believe it is outdated (does not apply to Che 7). Please reopen if you believe the issue is still relevant.

How to clone private projects from gitlab in Che 7?
