### ISSUE TITLE
Refactoring docs PR has erased and override some documentation 

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#215] opened 2017-04-26 08:20 UTC
Refactoring docs PR https://github.com/eclipse/che-docs/pull/149
has override documentation for intelligent commands.

There are probably other pages that have been updated between the time the PR has been opened, and the time it was merged.

**Comment by slemeur** [comment] 2017-04-27 15:57
I found that we are missing the workspace JSON Model page

**Comment by themr0c** [comment] 2020-03-12 10:04
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 10:04 UTC
Labels: Che-6, kind/bug, severity/P1
