### ISSUE TITLE
[WIP]Add the stack list to the Workspace Management > Stacks chapter

### ISSUE THREAD

**Issue by supriya-bharadwaj** [eclipse/che-docs#671] opened 2019-01-30 09:58 UTC
Add the stacks list to https://www.eclipse.org/che/docs/che-6/stacks.html#stack-overview.

**Comment by themr0c** [comment] 2020-03-12 09:57
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.

**Closed by themr0c** 2020-03-12 09:57 UTC
Labels: Che-6
